# -*- coding: utf-8 -*-
"""Day 5 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14PIiCyoO12uh8KwyrO2TkTpGS-pqEFla
"""

#Loops

#For Loop

#for item in list_of_items:
  #Do domething to each item

fruits = ["Apple", "Peach", "Pear"]
for fruit in fruits:
  print(fruit)
  print(fruit + " Pie")
print(fruits)
  # if fruit[0] == "P":
  #   print("start with a 'P'")
  # else:
  #   print("start with other letter")

#My Way
student_heights = input().split()
sum = 0
avg = 0
for n in range(0, len(student_heights)):
  student_heights[n] = int(student_heights[n])
  sum += student_heights[n]
  avg = round(sum / len(student_heights))
print(f"total height = {sum}")
print(f"number of students = {len(student_heights)}")
print(f"average height = {avg}")

#Coure Way
student_heights = input().split()
total_height = 0
for height in student_heights:
  total_height += int(height)
print(f"total height = {total_height}")

number_of_students = 0
for student in student_heights:
  number_of_students += 1
print(f"number of students = {number_of_students}")

average_height = round(total_height / number_of_students)
print(f"average height = {average_height}")

#My Way
student_scores = input().split()
max_num = 0
for n in range(0, len(student_scores)):
  student_scores[n] = int(student_scores[n])
  if max_num < student_scores[n]:
    max_num = student_scores[n]
print(f"The highest score in the class is: {max_num}")

#Course Way
student_scores = input().split()
for n in range(0, len(student_scores)):
  student_scores[n] = int(student_scores[n])

highest_score = 0
for score in student_scores:
  if score > highest_score:
    highest_score = score

print(f"The highest score in the class is: {highest_score}")

# fruits = ["Apple", "Peach", "Pear"]
# for fruit in fruits:
#   print(fruit)
#   print(fruit + " Pie")

#For Loop With Range
# for number in range(a, b):
#   print(number)

# for number in range(1, 11, 3):
#   print(number)

#range(start number, end number, jump by number)

total = 0
for number in range(1, 101):
  total += number
print(total)

#calculate the Even numbers
number = int(input("Enter A Number Till 100! "))
total = 0
for number in range(1, number + 1):
  if number % 2 == 0:
    total += number
print(total)

#FizzBuzz Game
for number in range(1, 16):
  if number % 3 == 0 and number % 5 == 0:
    print("Fizz Buzz")
  elif number % 3 == 0:
    print("Fizz")
  elif number % 5 == 0:
    print("Buzz")
  else:
    print(number)

import random
letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
numbers = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
symbols = ['!', '#', '$', '%', '&', '(', ')', '*', '+']

print("Welcome to the PyPassword Generator!")
nr_letters= int(input("How many letters would you like in your password?\n"))
nr_numbers = int(input(f"How many numbers would you like?\n"))
nr_symbols = int(input(f"How many symbols would you like?\n"))

# Eazy Level unrandomize

# password = ""

# for char in range(1, nr_letters + 1):
#   password += random.choice(letters)

# for char in range(1, nr_symbols + 1):
#   password += random.choice(symbols)

# for char in range(1, nr_numbers + 1):
#   password += random.choice(numbers)

# print(password)

#Hard Level randomize

password_list = []

for char in range(1, nr_letters +1):
  password_list.append(random.choice(letters))

for number in range(1, nr_numbers +1):
  password_list.append(random.choice(numbers))

for symbol in range(1, nr_symbols +1):
  password_list.append(random.choice(symbols))

print(password_list)
random.shuffle(password_list)
print(password_list)

password = ""
for char in password_list:
  password += char
print(f"Your Password is: {password}")