# -*- coding: utf-8 -*-
"""Day 2 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qYSKI7WbikKD2xrDzSvMYywWmaTuWCKP
"""

two_digit_number = input()
first_num = two_digit_number[0]
second_num = two_digit_number[1]
two_digit_number = int(first_num) + int(second_num)
print(two_digit_number)

3 + 5

7 - 4

3 * 2

6 / 3

2 ** 2

# PEMDASLR
# ()
# **
# *
# /
# +
# -

3 * (3 + 3) / 3 -3

height = input()
weight = input()

bmi = int(weight) / (float(height) * float(height))
int(bmi)

#round example
print(round(8 / 3))
#Round Example with how many number after the decimal point
print(round(8 / 3 , 2))
# Double division sign to be int and not float
print(8 // 3 )

result = 4 / 2
result /= 2
print(result)

score = 0
score += 1
print(score)

score = 0
height = 1.8
isWinning = True
#f-String helps us to print easelly without plus sign or converting types

print(f"your score is {score}, your height is {height}, you are winning is {isWinning}")

age = input()

years = 90 - int(age)
weeks = years * 52

print(f"You have {weeks} weeks left")

#If the bill was $150.00, split between 5 people, with 12% tip.

#Each person should pay (150.00 / 5) * 1.12 = 33.6
#Round the result to 2 decimal places = 33.60

#Tip: There are 2 ways to round a number. You might have to do some Googling to solve this.💪

#Write your code below this line 👇
print("Wellcome to the tip calculator!")

bill = float(input("What was the total bill? $"))
tip = int(input("How much tip would you like to give? 10, 12, or 15? "))
people = int(input("How many people to split the bill? "))

bill_with_tip = tip / 100 * bill + bill
bill_per_person = bill_with_tip / people
final_amount = round(bill_per_person, 2)
final_amount = "{:.2f}".format(bill_per_person)
print(f"Each person should pay: ${final_amount}")