# -*- coding: utf-8 -*-
"""Day 4 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g1mA8D9g4jCI9_bhS78_L2-sKkxPjwrs
"""

import random

random_integer = random.randint(1, 10)
print(random_integer)

random_float = random.random()
print(random_float)

random_float_5 = random_float * 5
print(random_float_5)

random_side = random.randint(0, 1)
if random_side == 1:
  print("Heads")
else:
  print("Tails")

#Lists
#             0          1       2    programing count
#fruits = ["Cherry", "Apple", "Pear"]
#              1         2       3    humen count

states_of_america = ["Delaware", "Pennsylvania", "New Jersey", "Georgia", "Connecticut", "Massachusetts", "Maryland", "South Carolina", "New Hampshire", "Virginia", "New York", "North Carolina", "Rhode Island",
                     "Vermont", "Kentucky", "Tennessee", "Ohio", "Louisiana", "Indiana", "Mississippi", "Illinois", "Alabama", "Maine", "Missouri", "Arkansas", "Michigan", "Florida", "Texas", "Iowa", "Wisconsin",
                     "California", "Minnesota", "Oregon", "Kansas", "West Virginia", "Nevada", "Nebraska", "Colorado", "North Dakota", "South Dakota", "Montana", "Washington", "Idaho", "Wyoming", "Utah", "Oklahoma",
                     "New Mexico", "Arizona", "Alaska", "Hawaii"]

# print(states_of_america[0])
# states_of_america.append("MosheMorad")
print(states_of_america)
# states_of_america.remove("MosheMorad")
# print(states_of_america)

dirty_dozen = ["Strawberries", "Spinach", "Kale", "Nectarines", "Apples", "Grapes", "Peaches", "Cherries", "Pears", "Tomatoes", "Celery", "Potatoes"]

#My Way
names = input("Enter you're names. ").split(", ")
# names = names_string.split(", ")
# print(names[0])
import random
num_items = len(names)
random_choice = random.randint(0,num_items - 1)
print(f"{names[random_choice]} is going to buy the meal today!")

#Course Way
names_string = input("Enter you're names. ")
names = names_string.split(", ")

import random

# Get the total number of items in list.
num_items = len(names)
# Generate random numbers between 0 and the last index.
random_choice = random.randint(0, num_items - 1)
# Choose and print a random name.
print(names[random_choice])

states_of_america = ["Delaware", "Pennsylvania", "New Jersey", "Georgia", "Connecticut", "Massachusetts", "Maryland",
                     "South Carolina", "New Hampshire", "Virginia", "New York", "North Carolina", "Rhode Island",
                     "Vermont", "Kentucky", "Tennessee", "Ohio", "Louisiana", "Indiana", "Mississippi", "Illinois",
                     "Alabama", "Maine", "Missouri", "Arkansas", "Michigan", "Florida", "Texas", "Iowa", "Wisconsin",
                     "California", "Minnesota", "Oregon", "Kansas", "West Virginia", "Nevada", "Nebraska", "Colorado",
                     "North Dakota", "South Dakota", "Montana", "Washington", "Idaho", "Wyoming", "Utah", "Oklahoma",
                     "New Mexico", "Arizona", "Alaska", "Hawaii"]

num_of_states = len(states_of_america)

print(states_of_america[num_of_states - 1])

#Regular List
# dirty_dozen = ["Strawberries", "Spinach", "Kale", "Nectarines", "Apples", "Grapes", "Peaches", "Cherries", "Pears", "Tomatoes", "Celery", "Potatoes"]

fruits = ["Strawberries", "Nectarines", "Apples", "Grapes", "Peaches", "Cherries", "Pears",]
vegetables = ["Spinach", "Kale", "Tomatoes", "Celery", "Potatoes"]

#Nested Lists
dirty_dozen = [fruits, vegetables]

print(dirty_dozen)

line1 = ["⬜️","️⬜️","️⬜️"]
line2 = ["⬜️","⬜️","️⬜️"]
line3 = ["⬜️️","⬜️️","⬜️️"]
map = [line1, line2, line3]
print("Hiding your treasure! X marks the spot.")
position = input() # Where do you want to put the treasure?
letter = position[0].lower()
abc = ["a", "b", "c"]
letter_index = abc.index(letter)
number_index = int(position[1]) - 1
map[number_index][letter_index] = "X"

print(f"{line1}\n{line2}\n{line3}")

import random
# Rock Paper Scissors Lizard Spock ASCII Art
#

# Rock
rock = '''
    _______
---'   ____)
      (_____)
      (_____)
      (____)
---.__(___)
'''

# Paper
paper = '''
    _______
---'   ____)____
          ______)
          _______)
         _______)
---.__________)
'''

# Scissors
scissors = '''
    _______
---'   ____)____
          ______)
       __________)
      (____)
---.__(___)
'''

# Lizard
lizard = '''
---.___________
        _______)
---.________)
'''

# Spock
spock = '''
    ⌠⌒|
 ⌠⌒⌉| |   ◜﹆◜﹆
 | ||⩧|  / // /
 |_|| | /-//=/
 | || |/ // /
 ( || | // /
 |         .______
 |         __⫫____)
  |       |
'''

game = [rock, paper, scissors, lizard, spock]

choice = int(input("What do you choose? Type 1 for Rock, 2 for Paper, 3 for scissors, 4 for Lizard or 5 for Spock "))

user_choice = choice -1

if user_choice >= 5 or user_choice < 0:
  print("You typed an invalid number, You Lose!")
else:
  user_choice_game = game[user_choice]

  print(user_choice_game)

  comp_choice = random.randint(0, 4)

  comp_choice_game = game[comp_choice]

  print("Computre Chose:")

  print(comp_choice_game)

  if user_choice == 0 and comp_choice == 2:
    print("Rock crushes Scissors")
    print("You Win!")
  elif user_choice == 3 and comp_choice == 4:
    print("Lizard poisons Spock")
    print("You Win!")
  elif user_choice == 1 and comp_choice == 4:
    print("Paper disproves Spock")
    print("You Win!")
  elif user_choice == 2 and comp_choice == 3:
    print|("Scissors decapitates Lizard")
    print("You Win!")
  elif user_choice == 2 and comp_choice == 4:
    print("You Win!")
  elif comp_choice == 0 and user_choice == 2:
    print("Rock crushes Scissors")
    print("You Lose!")
  elif comp_choice == 3 and user_choice == 4:
    print("Lizard poisons Spock")
    print("You Lose!")
  elif comp_choice == 1 and user_choice == 4:
    print("Paper disproves Spock")
    print("You Lose!")
  elif comp_choice == 2 and user_choice == 3:
    print|("Scissors decapitates Lizard")
    print("You Lose!")
  elif comp_choice > user_choice:
    print("You Lose!")
  elif user_choice > comp_choice:
    print("You Win!")
  elif comp_choice == user_choice:
    print("It's A Draw!")

# Scissors cuts Paper
# Paper covers Rock
# Rock crushes Lizard
# Lizard poisons Spock
# Spock smashes Scissors
# Scissors decapitates Lizard
# Lizard eats Paper
# Paper disproves Spock
# Spock vaporizes Rock
# Rock crushes Scissors

import random
# Rock Paper Scissors Game
#

# Rock
rock = '''
    _______
---'   ____)
      (_____)
      (_____)
      (____)
---.__(___)
'''

# Paper
paper = '''
    _______
---'   ____)____
          ______)
          _______)
         _______)
---.__________)
'''

# Scissors
scissors = '''
    _______
---'   ____)____
          ______)
       __________)
      (____)
---.__(___)
'''

game = [rock, paper, scissors]

choice = int(input("What do you choose? Type 1 for Rock, 2 for Paper or 3 for scissors "))

user_choice = choice -1
if user_choice >= 3 or user_choice < 0:
  print("You typed an invalid number, You Lose!")
else:
  user_choice_game = game[user_choice]

  print(user_choice_game)

  comp_choice = random.randint(0, 2)

  comp_choice_game = game[comp_choice]

  print("Computre Chose:")

  print(comp_choice_game)

  if user_choice == 0 and comp_choice == 2:
    print("You Win!")
  elif comp_choice == 0 and user_choice == 2:
    print("You Lose!")
  elif comp_choice > user_choice:
    print("You Lose!")
  elif user_choice > comp_choice:
    print("You Win!")
  elif comp_choice == user_choice:
    print("It's A Draw!")